name: Build client.dll + injector.exe

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive   # اگر ساب‌ماژول داری مفید است

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - uses: lukka/get-cmake@latest

      - name: Generate project
        run: python create_account.py

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: alt-manager-binaries
          path: |
            build/client.dll
            build/injector.exe
